/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estudiantes;

import java.util.Set;
import javax.swing.DefaultListModel;

/**
 *
 * @author HP PORTATIL
 */
public class Buscador extends javax.swing.JFrame {

    private static DefaultListModel ModeloListaCodigos = new DefaultListModel();
    
    private int tipo;
    
    /**
     * Creates new form Buscador
     */
    public Buscador(int tipo) {
        initComponents();
        ListaCodigos.setModel(ModeloListaCodigos);
        this.tipo = tipo;
        switch (tipo){
            case 1:
                this.btnConfirmar.setText("Modificar");
                break;
            case 2:
                this.btnConfirmar.setText("Consultar");
                break;
            case 3:
                this.btnConfirmar.setText("Borrar");
                break;
        }
        MostrarListaCodigos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaCodigos = new javax.swing.JList<>();
        txtfillBuscarCodigo = new javax.swing.JTextField();
        EnunCodigoEstu = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ListaCodigos);

        txtfillBuscarCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfillBuscarCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfillBuscarCodigoKeyTyped(evt);
            }
        });

        EnunCodigoEstu.setText("Codigo del Estudiante");

        btnConfirmar.setText("Modificar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(EnunCodigoEstu))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtfillBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnConfirmar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EnunCodigoEstu)
                        .addGap(18, 18, 18)
                        .addComponent(txtfillBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnCancelar)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        int NumeroIngreso = Integer.parseInt(txtfillBuscarCodigo.getText());
        
        if(GestionEstudiantes.getMapa().containsKey(NumeroIngreso)){
            switch (tipo){
            case 1:
                ModificarEstudiante ventanaM = new ModificarEstudiante(NumeroIngreso, GestionEstudiantes.getMapa().get(NumeroIngreso));
                ventanaM.setVisible(true);
                break;
            case 2:
                Consultar ventanaC = new Consultar(NumeroIngreso, GestionEstudiantes.getMapa().get(NumeroIngreso));
                ventanaC.setVisible(true);
                break;
            case 3:
                AdvertenciaBorrar ventanaB = new AdvertenciaBorrar(NumeroIngreso, GestionEstudiantes.getMapa().get(NumeroIngreso));
                ventanaB.setVisible(true);
                break;
            }
            dispose();
            ModeloListaCodigos.removeAllElements();
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
        ModeloListaCodigos.removeAllElements();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtfillBuscarCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfillBuscarCodigoKeyTyped
        char i = evt.getKeyChar();
        
        if (!Character.isDigit(i) || txtfillBuscarCodigo.getText().length()==6){
            evt.consume();
        }else{
            RefrescarListaCodigosTyped(i);
        }
    }//GEN-LAST:event_txtfillBuscarCodigoKeyTyped

    private void txtfillBuscarCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfillBuscarCodigoKeyPressed
        char i = evt.getKeyChar();
        
        if (i=='\b'){
            RefrescarListaCodigosDeled();
        }
    }//GEN-LAST:event_txtfillBuscarCodigoKeyPressed

    private void RefrescarListaCodigosTyped(char c) {
        
        int numeroEscrito = Integer.parseInt(txtfillBuscarCodigo.getText()+c);
        int tamañoNumero = Digitos(numeroEscrito);
        Set<Integer> Codigos = GestionEstudiantes.getMapa().keySet();
        
        ModeloListaCodigos.removeAllElements();
        if(!("".equals(txtfillBuscarCodigo.getText()+c))){
            for(Integer codigo: Codigos){
                if(UltimosDigitos(codigo,tamañoNumero) == numeroEscrito){
                    String NombreEstudiante = GestionEstudiantes.getMapa().get(codigo).getNombres();
                    ModeloListaCodigos.addElement(codigo+": "+NombreEstudiante);
                }
            }
        }
    }
    
    public void RefrescarListaCodigosDeled(){
        
        String numeroEscritoAntes = txtfillBuscarCodigo.getText();
        int tamañoNumeroAntes = numeroEscritoAntes.length();
        Set<Integer> Codigos = GestionEstudiantes.getMapa().keySet();
        
        ModeloListaCodigos.removeAllElements();
        
        if(tamañoNumeroAntes<=1){
            
            MostrarListaCodigos();
            
        }else{
            
            for(Integer codigo: Codigos){
                
                String numeroEscritoDespues = numeroEscritoAntes.substring(0, numeroEscritoAntes.length()-1);
                int tamañoNumeroDespues = tamañoNumeroAntes-1;
                
                if(UltimosDigitos(codigo,tamañoNumeroDespues) == Integer.parseInt(numeroEscritoDespues)){
                    String NombreEstudiante = GestionEstudiantes.getMapa().get(codigo).getNombres();
                    ModeloListaCodigos.addElement(codigo+": "+NombreEstudiante);
                }
                
            }
            
        }
    }
    
    public void MostrarListaCodigos(){
        Set<Integer> Codigos = GestionEstudiantes.getMapa().keySet();
        
        for(Integer codigo: Codigos){
                String NombreEstudiante = GestionEstudiantes.getMapa().get(codigo.intValue()).getNombres();
                ModeloListaCodigos.addElement(codigo.intValue()+": "+NombreEstudiante);
            }
    }
    
    private int Digitos(int numero){
        String numeroComoString = String.valueOf(numero);
        int cantidadDigitos = numeroComoString.length();
        
        return cantidadDigitos;
    }
    
    private int UltimosDigitos(int numero, int digitos){
        
        String numeroString = String.valueOf(numero);
        numeroString = numeroString.substring(0, digitos);
        int ultimosDigitos = Integer.parseInt(numeroString);
        
        return ultimosDigitos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnunCodigoEstu;
    private javax.swing.JList<String> ListaCodigos;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnConfirmar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtfillBuscarCodigo;
    // End of variables declaration//GEN-END:variables
}
