/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estudiantes;

import java.util.HashMap;

/**
 *
 * @author HP PORTATIL
 */
public class Consultar extends javax.swing.JFrame {
    
    private int codigo;
    
    public Consultar(int codigo, Estudiante estudiante) {
        initComponents();
        this.codigo = codigo;
        this.txtCodigo.setText(String.valueOf(codigo));
        this.txtNombres.setText(estudiante.getNombres());
        this.txtApellidos.setText(estudiante.getApellidos());
        this.txtDireccion.setText(estudiante.getDireccion());
        this.txtTelefono.setText(String.valueOf(estudiante.getTelefono()));
        this.txtCarrera.setText(estudiante.getCarrera());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnunCodigo = new javax.swing.JLabel();
        EnunNombres = new javax.swing.JLabel();
        EnunApellidos = new javax.swing.JLabel();
        EnunDireccion = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        EnunCarrera = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JToggleButton();
        TituloRegistro = new javax.swing.JLabel();
        ErrorCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JLabel();
        txtNombres = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EnunCodigo.setText("Codigo:");

        EnunNombres.setText("Nombres:");

        EnunApellidos.setText("Apellidos:");

        EnunDireccion.setText("Direccion:");

        Telefono.setText("Telefono:");

        EnunCarrera.setText("Carrera:");

        btnCancelar.setText("Atras");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        TituloRegistro.setText("Registrar Estudiante");

        txtCodigo.setText("Codigotxt");

        txtNombres.setText("Nombrestxt");

        txtApellidos.setText("Apellidostxt");

        txtDireccion.setText("Direcciontxt");

        txtTelefono.setText("Telefonotxt");

        txtCarrera.setText("Carreratxt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnunApellidos)
                            .addComponent(EnunNombres)
                            .addComponent(EnunCodigo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtApellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EnunCarrera))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCodigo)
                                        .addGap(64, 64, 64))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombres)
                                        .addGap(36, 36, 36)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EnunDireccion)
                                    .addComponent(Telefono))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ErrorCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion)
                            .addComponent(txtTelefono)
                            .addComponent(txtCarrera)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(TituloRegistro)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TituloRegistro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnunCodigo)
                    .addComponent(ErrorCodigo)
                    .addComponent(txtCodigo)
                    .addComponent(EnunDireccion)
                    .addComponent(txtDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnunNombres)
                    .addComponent(Telefono)
                    .addComponent(txtNombres)
                    .addComponent(txtTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnunApellidos)
                    .addComponent(EnunCarrera)
                    .addComponent(txtApellidos)
                    .addComponent(txtCarrera))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EnunApellidos;
    private javax.swing.JLabel EnunCarrera;
    private javax.swing.JLabel EnunCodigo;
    private javax.swing.JLabel EnunDireccion;
    private javax.swing.JLabel EnunNombres;
    private javax.swing.JLabel ErrorCodigo;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel TituloRegistro;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JLabel txtApellidos;
    private javax.swing.JLabel txtCarrera;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtNombres;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
